### ISSUE TITLE
Handful of ruby issues

### ISSUE THREAD

**Issue by jasonrowland86** [jasonrowland86/Project-4-App#1]
1. Trying to conditionally render in an erb file:

```ruby
<% if @plants %>
        <% @plants.each do |plant| %>
          <div class="plant">
            <%= link_to plant.name, plant_path(plant) %>
          </div>
        <% end %>
      <% else %>
        <h3>You have no plants of this type</h3>
      <% end %>
```
and controller:

```ruby
def medium
    plants = current_user.plants
    @plants = plants.select { |plant| plant.category == 'Medium' }
  end
```
in my case @plants should be empty and "You have no plants of this type" should render. But it doesn't display either.

2. My flashMessages are not showing anymore.

3. Also having trouble linking some additional js assets in, I tried linking them correctly in my ` application.html.erb ` and then doing this ` Rails.application.config.assets.precompile += %w( bootstrap.min.js ) ` in my ` config/initializers/assets.rb `

https://stackoverflow.com/questions/17795053/if-else-statements-in-html-erb-in-views

**Comment by aribrenner** [comment]
@jasonrowland86  in ruby only `nil` and `false` are falsy. `@plants` is neither of those so it must be truthy. so instead of checking `if @plants`, check `if @plants.present?`

also: use the powers of active record! `current_user.plants.where(category: 'Medium')`. don't need to bother with the `select`

**Comment by aribrenner** [comment]
for questions 2 and 3, i would need more information. 

2: you should display your flash message in `application.html.erb`
3: google how to do this. there are a few different options

**Comment by jasonrowland86** [comment]
Thanks!!! I understand that now, it was truthy so it rendered the plants list with no plants, and never registered as falsey.

I dont know what happened to the flashMessages and I dont have any info to help with that other than, my guess is that they are there but not showing because of some css? 

I'll see what I can do. Thanks!
